# Generated by Django 4.2.7 on 2023-11-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('a', 'Analog'), ('d', 'Digital'), ('h', 'Hybrid')], max_length=1)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
