# Generated by Django 4.2.7 on 2023-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='image',
        ),
        migrations.AddField(
            model_name='watch',
            name='is_mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='mainImage',
            field=models.ImageField(default='images/main/default.jpg', upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='watch',
            name='secondImage',
            field=models.ImageField(default='images/sec/default.jpg', upload_to='images/sec/'),
        ),
    ]
