# Generated by Django 4.2.7 on 2023-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_rename_mainimage_watch_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='main_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='watch',
            name='second_image',
            field=models.CharField(max_length=300),
        ),
    ]
